### ISSUE TITLE
Commit style

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt-organizer#10]
Hi,

I appreciate your work on organizer.
It would be cool if you could take a look at how other (LXQt) projects do their commits.
So far you use git very strangely :)

And please read https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53 I think that one can help you too.

**Comment by luis-pereira** [comment]
@jubalh I completely agree with it.
By it, I meant, your comment.

**Comment by jubalh** [comment]
@crispinalan you keep on doing more commits in the bad style. Just now you did: https://github.com/lxqt/organizer/commit/5bb83dd222120fd2191b83a434cc36fe2dd6f29f

Please take some time to read what we have requested here.

**Comment by ghost** [comment]
Yes I looking into this.

**Comment by jubalh** [comment]
Much better @crispinalan.
Now all the things listed as:
- Reorganised menu into logical groupings
- Removed experimental themes
[feat]: new option for displaying appointment items separated with newlines
[feat]: minimum calendar font size limted set to 8
[feat]: maximum calendar font size limited to 36
[fix]: month-year label font size now increases/decreases
[fix]: repeat appointment default category fixed
[docs]: about window updated with keyboard shortcut information
[docs]: removed point release information from README.md

Should actually be individual commits. A git commit is not equal to a release.
So while developing you could commit each related change as one commit. And after a few commits you create a new version.

For example you can see that @agaida uses GitHub to plan a new release.
He organizes several issues and only after all the decided should go into the next release are done, he creates a new release.

This also is true for point releases. Which mostly mean a bugfix release or a release with minor changes or no big new features. So 1.0 to 2.0 is a new release. 1.0 to 1.1 is a point release. At least thats how some people use this word.

**Comment by ito32bit** [comment]
Example of version number: https://semver.org/  
Example of commit message: https://chris.beams.io/posts/git-commit/  
These two are in my bookmarks.

**Comment by tsujan** [comment]
In short, the commit message should be so that everyone could understand the *single* purpose of the commit by reading it at any time.

**Comment by ghost** [comment]
Regarding the commit of 30 Jan 2020 I was using the Rapid Application Development  [RAD]( https://blog.capterra.com/what-is-rapid-application-development/) as I had a chunk of free time to work on the project.
