### ISSUE TITLE
FTBFS with Qt5.14.0

### ISSUE THREAD

**Issue by luis-pereira** [lxqt/lxqt-organizer#12]
FTBFS with latest git and Qt5.14.0
Log [here](https://pastebin.com/rF8aTZ7Z)

##### Expected Behavior
Build 

##### Current Behavior
Does not build

##### Steps to Reproduce (for bugs)
cmake .. && ninja

##### System Information

* Distribution & Version: Manjaro
* Kernel: not relevant
* Qt Version: 5.41.0
* liblxqt Version: git
* lxqt-build-tools Version: git
* Package version: git

**Comment by ghost** [comment]
I am using Debian 10 to develop LXQt/Organizer. My version of Qt is

qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/x86_64-linux-gnu

I am using  Qt Creator 4.8.2. Maybe someone from the arch community can add some light on this problem.

When I tested the Manjaro ARM LXQt  Pi4  image on my Raspberry Pi I used yay to install lxqt-organiser (yay -S lxqt-organizer) from the package that Librewish produced.

**Comment by luis-pereira** [comment]
maybe an update issue. I will try again.
