### ISSUE TITLE
additional features

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-organizer#13]
some features you could add
1. reminder for the todo's
2. time related features such as 
stopwatch,timer,worldcolck,alarm.
3. weather info in calendar for today and upcoming days.

**Comment by ghost** [comment]
Yes I plan to implements many of these features in later point releases. Currently stabilising the v005 point release which has the new calendar code. Once this is done I will do some more research to see how these features can best be implemented. Thanks for the suggestions.

**Comment by jubalh** [comment]
There is no "point" in `v005` :-)

**Comment by tsujan** [comment]
Will be archived.
