### ISSUE TITLE
Huge sizes out of nowhere

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/lxqt-organizer#20]
##### Expected Behavior
The fonts and sizes look nice
##### Current Behavior

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/19782228/87228220-671b8400-c3a8-11ea-9adb-c2274c5803ad.png">

##### Steps to Reproduce (for bugs)

Clone git repo, compile and run

##### System Information

* Distribution & Version: Xubuntu 20.04
* Kernel: 5.4.0-40
* Qt Version:  Qt 5.12.8

**Comment by tsujan** [comment]
Haven't read the code but, IMHO, sizes should be left to the DE or the widget style. At most, texts could be made bold and/or italic if really needed.

**Comment by shlyakpavel** [comment]
Well, I have found an option to change font sizes. However, as @tsujan mentioned above it would be sane to keep system font sizes by default

**Comment by shlyakpavel** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/19782228/87229001-65a08a80-c3ad-11ea-8cf9-ce1803655c1d.png">
These huge bold labels make me sooo scared

**Comment by ghost** [comment]
Press the "r" key to reset font size ( "f" key to increase font size and "d" key to decrease)

**Comment by tsujan** [comment]
Will be archived.
