### ISSUE TITLE
Build error: No rule to make target 'icons/icon-calendar.png', needed by 'src/qrc_icons.cpp'. Stop.

### ISSUE THREAD

**Issue by ghost** [lxqt/lxqt-organizer#30]
While building, make throws an error as shown in the title. Here's the output:
```
Scanning dependencies of target organizer_autogen
[  2%] Automatic MOC and UIC for target organizer
[  2%] Built target organizer_autogen
[  4%] Generating ui_mainwindow.h
[  6%] Generating moc_dialogappointment.cpp
[  8%] Generating moc_dialogappointmentupdate.cpp
[ 10%] Generating moc_dialogcontact.cpp
[ 12%] Generating moc_dialogpreferences.cpp
[ 14%] Generating moc_dialogrepeatappointment.cpp
[ 16%] Generating moc_dialogupcomingbirthdays.cpp
[ 18%] Generating moc_dialogupcomingschedule.cpp
[ 20%] Generating moc_mainwindow.cpp
[ 22%] Generating moc_proxymodelcontacts.cpp
make[2]: *** No rule to make target '/home/tmoment/random/lxqt-organizer-git/src/organizer/src/icons/icon-calendar.png', needed by 'src/qrc_icons.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:162: src/CMakeFiles/organizer.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

##### Possible Solution
Adding a target in `src/CMakeLists.txt` for icon files.

##### Context
I maintain the AUR packages [lxqt-desktop-git](https://aur.archlinux.org/packages/lxqt-desktop-git) and [lxqt-organizer-git](https://aur.archlinux.org/packages/lxqt-organizer-git)

##### System Information

* Distribution & Version: Arch Linux
* Kernel: linux-pf-generic 5.10.4
* Qt Version: 5.15.2 (and 6.0.0)
* liblxqt Version: 0.16.0.7.ga4db612-1
* lxqt-build-tools Version: 0.8.0.3.g77c48a9-1
* Package version: Building from latest commit (0.7.4)

**Comment by zsigmondszilveszter** [comment]
There is a patch suggested in the #26 PR. The problem is that's not the only issue here, the project doesn't compile even after the patch is applied. This error persist from at least September 2020 and no one noticed. This repository is quite abandoned, at least it seems like to me. I try to fix the build problems and hope there are active people who are allowed to merge.

**Comment by tsujan** [comment]
Organizer isn't developed anymore. See https://github.com/lxqt/organizer/issues/27#issuecomment-665959988.

**Comment by ghost** [comment]
Amazing. absolutely incredible. Guess I'll have to remove that package

**Comment by tsujan** [comment]
> Amazing. absolutely incredible.

The original author made the team work practically impossible and, in the end, told us to remove it from LXQt. It's here only in case he changes his mind.
