### ISSUE TITLE
Image file missing to build the source

### ISSUE THREAD

**Issue by thiyashoksanju** [lxqt/lxqt-organizer#32]
- Trying to build **Organizer** repository with CMake & make
- CMake was successful but make command shows an error like **No rule to make target '..src/icons/icon_calendar.png' needed by 'src.qrc_icons.cpp'**
- the specified png image is missing in the original repository

**Expected Behavior**

- make command should be successful
- Specifc image file must be present

**Current Behavior**
- make command fails
- Specifc image file is missing

**Possible Solution**

- Include the missing png file

**Steps to Reproduce (for bugs)**

1. Download organizer repository
2. Perform CMake and install required dependent libraries along with LXQT repositories
3. Perform Make command

**Context**

- Iam performing the process of building every lxqt repositories in my local system, this error put a break to my process

**System Information**

* Distribution & Version: Lubuntu 22.04 (running as VM)
* Kernel: 5.15.0-27-generic
* Qt Version: 5.15.3
* liblxqt Version: 1.1.0 / 2022-04-15
* lxqt-build-tools Version: 0.11.0 / 2022-04-15
* Package version: 0.7.4

**Comment by monishaaaaaaram** [comment]
I'm also facing the same issue.  Can't able to build the Organizer repository because of that missing png file. 
It is showing like this:
 "  make[2]: *** No rule to make target '../src/icons/icon-calendar.png', needed by 'src/qrc_icons.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:143: src/CMakeFiles/organizer.dir/all] Error 2
make: *** [Makefile:136: all] Error 2 "

**Comment by tsujan** [comment]
→ https://github.com/lxqt/organizer/issues/31

**Comment by thiyashoksanju** [comment]
@tsujan please update as "no longer supported either in description or about column just like the community did for [liblxqt_mount_deprecated](https://github.com/lxqt/liblxqt-mount-deprecated)"
So that people will not spend time on building this repository in future

**Comment by tsujan** [comment]
I'll try to archive it. Should first close all PRs and issues.
